/**
 * MoaSpace API Type Definitions
 * Auto-generated by openapi-typescript: `npm --workspace=@moaspace/api-types run api:gen`
 */

export interface paths {
  '/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              name: string;
              version: string;
              status: string;
              timestamp: string;
            };
          };
        };
      };
    };
  };
  '/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
              uptime: number;
              timestamp: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;
export type components = Record<string, never>;
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
