/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API information */
        get: operations["AppController_getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk dengan email dan kata sandi */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inisiasi login Google OAuth 2.0 (Redirect ke consent screen Google) */
        get: operations["AuthController_googleRedirect"];
        put?: never;
        /** Masuk dengan Google ID Token (One Tap / Popup SDK) */
        post: operations["AuthController_googleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dapatkan URL otorisasi Google OAuth 2.0 */
        get: operations["AuthController_getGoogleAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback redirect langsung dari Google OAuth 2.0 */
        get: operations["AuthController_googleCallbackGet"];
        put?: never;
        /** Tukarkan kode otorisasi Google OAuth 2.0 dengan sesi (BFF) */
        post: operations["AuthController_googleCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Perbarui access token dengan refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dan cabut sesi */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ambil data profil pengguna yang sedang login */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Perbarui nama profil pengguna yang sedang login */
        patch: operations["AuthController_updateProfile"];
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah kata sandi pengguna yang sedang login */
        patch: operations["AuthController_changePassword"];
        trace?: never;
    };
    "/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aktivasi akun anggota baru dengan token dan kata sandi */
        post: operations["AuthController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Minta tautan reset kata sandi melalui email */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset kata sandi dengan token valid */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ambil daftar activity log dengan pencarian, filter, sorting & paginasi (Super Admin & Koordinator Mahasiswa Unit) */
        get: operations["ActivityLogsController_getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar seluruh divisi KKN beserta jumlah anggota & koordinator */
        get: operations["DivisionsController_findAll"];
        put?: never;
        /** Buat divisi baru (Khusus Super Admin & Koordinator Mahasiswa Unit) */
        post: operations["DivisionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail satu divisi beserta daftar anggotanya */
        get: operations["DivisionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Perbarui nama, slug, atau toggle approval request divisi (Super Admin & Kormanit) */
        patch: operations["DivisionsController_update"];
        trace?: never;
    };
    "/divisions/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tambah anggota ke dalam divisi (Koordinator Divisi, Super Admin, Kormanit) */
        post: operations["DivisionsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/divisions/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hapus anggota dari divisi (Koordinator Divisi, Super Admin, Kormanit) */
        delete: operations["DivisionsController_removeMember"];
        options?: never;
        head?: never;
        /** Ubah peran anggota dalam divisi (Koordinator Divisi, Super Admin, Kormanit) */
        patch: operations["DivisionsController_updateMemberRole"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar seluruh anggota tim KKN beserta divisi & role (Super Admin & Koordinator Mahasiswa Unit) */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Daftarkan anggota baru tim KKN dan kirim tautan aktivasi (Super Admin & Koordinator Mahasiswa Unit) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah status aktif/nonaktif anggota (Super Admin & Koordinator Mahasiswa Unit) */
        patch: operations["UsersController_updateStatus"];
        trace?: never;
    };
    "/users/{id}/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tambahkan anggota ke divisi lain (Multi-divisi) (Super Admin & Koordinator Mahasiswa Unit) */
        post: operations["UsersController_addDivision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/divisions/{divisionId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah role anggota di divisi tertentu (Super Admin & Koordinator Mahasiswa Unit) */
        patch: operations["UsersController_updateDivisionRole"];
        trace?: never;
    };
    "/users/{id}/divisions/{divisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hapus keanggotaan divisi seorang anggota (Super Admin & Koordinator Mahasiswa Unit) */
        delete: operations["UsersController_removeDivision"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/divisions/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pindahkan anggota dari satu divisi ke divisi lain (Super Admin & Koordinator Mahasiswa Unit) */
        post: operations["UsersController_moveDivision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/global-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah hak akses Koordinator Mahasiswa Unit (Super Admin & Koordinator Mahasiswa Unit) */
        patch: operations["UsersController_updateGlobalRole"];
        trace?: never;
    };
    "/users/{id}/resend-activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kirim ulang link aktivasi untuk anggota yang belum aktif (Super Admin & Koordinator Mahasiswa Unit) */
        post: operations["UsersController_resendActivation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar epic pekerjaan divisi / lintas divisi beserta progres dinamis */
        get: operations["EpicsController_findAll"];
        put?: never;
        /** Buat epic baru (Koordinator Divisi untuk scope DIVISION; Super Admin/Kormanit untuk CROSS) */
        post: operations["EpicsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/epics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail satu epic beserta seluruh story & task */
        get: operations["EpicsController_findOne"];
        put?: never;
        post?: never;
        /** Hapus epic (Khusus Super Admin & Kormanit) */
        delete: operations["EpicsController_delete"];
        options?: never;
        head?: never;
        /** Perbarui judul, tanggal, proker, atau tutup/buka epic */
        patch: operations["EpicsController_update"];
        trace?: never;
    };
    "/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar deliverable stories per divisi atau per epic beserta progres dinamis */
        get: operations["StoriesController_findAll"];
        put?: never;
        /** Buat story baru (Koordinator divisi pemilik, Super Admin, Kormanit) */
        post: operations["StoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail satu story beserta seluruh task perorangan */
        get: operations["StoriesController_findOne"];
        put?: never;
        post?: never;
        /** Hapus story */
        delete: operations["StoriesController_delete"];
        options?: never;
        head?: never;
        /** Perbarui deliverable story, kriteria selesai, target tanggal, atau status penutupan */
        patch: operations["StoriesController_update"];
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar seluruh task dengan filter story, divisi, status, atau assignee */
        get: operations["TasksController_findAll"];
        put?: never;
        /** Buat task baru di dalam story */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail satu task beserta riwayat log audit perubahan */
        get: operations["TasksController_findOne"];
        put?: never;
        post?: never;
        /** Hapus task dari story (Khusus Koordinator Divisi / Admin) */
        delete: operations["TasksController_delete"];
        options?: never;
        head?: never;
        /** Perbarui task, pindahkan status kanban, atau ubah assignee */
        patch: operations["TasksController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Registered user email
             * @example admin@moaspace.com
             */
            email: string;
            /**
             * @description User password (minimum 8 characters)
             * @example admin123
             */
            password: string;
        };
        GoogleCallbackDto: {
            /** @description Kode otorisasi dari Google OAuth 2.0 consent */
            code: string;
            /** @description Redirect URI yang dipakai saat request otorisasi awal */
            redirectUri?: string;
        };
        GoogleAuthDto: {
            /** @description Google ID token from Google OAuth popup / library */
            idToken: string;
        };
        UpdateProfileDto: {
            /**
             * @description Nama lengkap baru pengguna
             * @example Ahmad Fauzi
             */
            name: string;
        };
        ChangePasswordDto: {
            /** @description Kata sandi saat ini (wajib jika akun sebelumnya sudah memiliki kata sandi) */
            currentPassword?: string;
            /**
             * @description Kata sandi baru (minimal 8 karakter)
             * @example rahasia123
             */
            newPassword: string;
        };
        ActivateDto: {
            /** @description One-time activation token received via email */
            token: string;
            /**
             * @description New password (minimum 8 characters)
             * @example NewSecretPass123
             */
            password: string;
        };
        ForgotPasswordDto: {
            /**
             * @description Registered user email
             * @example user@moaspace.com
             */
            email: string;
        };
        ResetPasswordDto: {
            /** @description Password reset token received via email */
            token: string;
            /**
             * @description New password (minimum 8 characters)
             * @example NewPassword123
             */
            password: string;
        };
        CreateDivisionDto: {
            /**
             * @description Nama divisi
             * @example Media Kreatif
             */
            name: string;
            /**
             * @description Slug unik divisi URL-friendly
             * @example media-kreatif
             */
            slug?: string;
            /**
             * @description Status aktifasi persetujuan request pekerjaan untuk divisi ini
             * @default false
             */
            requestApprovalEnabled: boolean;
        };
        UpdateDivisionDto: {
            /**
             * @description Nama divisi
             * @example Media & Publikasi Kreatif
             */
            name?: string;
            /**
             * @description Slug unik divisi URL-friendly
             * @example media-publikasi-kreatif
             */
            slug?: string;
            /** @description Status aktifasi persetujuan request pekerjaan untuk divisi ini */
            requestApprovalEnabled?: boolean;
        };
        AddDivisionMemberDto: {
            /** @description ID pengguna yang akan ditambahkan ke divisi */
            userId: string;
            /**
             * @description Peran dalam divisi (MEMBER atau COORDINATOR)
             * @default MEMBER
             * @enum {string}
             */
            role: "MEMBER" | "COORDINATOR";
        };
        UpdateDivisionMemberRoleDto: {
            /**
             * @description Peran baru dalam divisi (MEMBER atau COORDINATOR)
             * @enum {string}
             */
            role: "MEMBER" | "COORDINATOR";
        };
        CreateUserDto: {
            /**
             * @description Alamat email anggota
             * @example ahmad@moaspace.com
             */
            email: string;
            /**
             * @description Nama lengkap anggota
             * @example Ahmad Fauzi
             */
            name: string;
            /** @description ID divisi penempatan */
            divisionId: string;
            /**
             * @description Role anggota di divisi atau Koordinator Mahasiswa Unit (Akses Penuh)
             * @example MEMBER
             * @enum {string}
             */
            role: "MEMBER" | "COORDINATOR" | "KORMANIT" | "KOORDINATOR_MAHASISWA_UNIT";
        };
        UpdateUserStatusDto: {
            /**
             * @description Status pengguna
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        AddUserDivisionDto: {
            /** @description ID divisi yang akan ditambahkan */
            divisionId: string;
            /**
             * @description Role anggota di divisi ini
             * @example MEMBER
             * @enum {string}
             */
            role: "MEMBER" | "COORDINATOR";
        };
        UpdateUserDivisionRoleDto: {
            /**
             * @description Role baru anggota di divisi ini
             * @example COORDINATOR
             * @enum {string}
             */
            role: "MEMBER" | "COORDINATOR";
        };
        MoveUserDivisionDto: {
            /** @description ID divisi asal */
            fromDivisionId: string;
            /** @description ID divisi tujuan */
            toDivisionId: string;
            /**
             * @description Role di divisi tujuan (default mengikuti role di divisi asal)
             * @enum {string}
             */
            role?: "MEMBER" | "COORDINATOR";
        };
        UpdateUserGlobalRoleDto: {
            /**
             * @description Status peran Koordinator Mahasiswa Unit (akses penuh setara Super Admin)
             * @example true
             */
            isKormanit: boolean;
        };
        CreateEpicDto: {
            /**
             * @description Judul epic pekerjaan
             * @example Penyusunan Konten Edukasi Digital
             */
            title: string;
            /** @description Deskripsi lengkap epic */
            description?: string;
            /**
             * @description Tanggal mulai (ISO8601)
             * @example 2026-10-01T00:00:00.000Z
             */
            startDate?: string;
            /**
             * @description Tanggal selesai (ISO8601)
             * @example 2026-10-31T23:59:59.000Z
             */
            endDate?: string;
            /**
             * @description Tag program kerja KKN terkait
             * @example PROKER-01
             */
            prokerTag?: string;
            /**
             * @description Cakupan epic (DIVISION = khusus satu divisi, CROSS = lintas divisi)
             * @default DIVISION
             * @enum {string}
             */
            scope: "DIVISION" | "CROSS";
            /** @description ID divisi pemilik (wajib jika scope DIVISION) */
            ownerDivisionId?: string;
            /** @description Daftar ID divisi yang berpartisipasi (khusus jika scope CROSS) */
            participatingDivisionIds?: string[];
        };
        UpdateEpicDto: {
            /** @description Judul epic pekerjaan */
            title?: string;
            /** @description Deskripsi lengkap epic */
            description?: string;
            /** @description Tanggal mulai (ISO8601) */
            startDate?: string;
            /** @description Tanggal selesai (ISO8601) */
            endDate?: string;
            /** @description Tag program kerja KKN */
            prokerTag?: string;
            /** @description ID divisi pemilik (khusus scope DIVISION) */
            ownerDivisionId?: string;
            /** @description Daftar ID divisi yang berpartisipasi (khusus scope CROSS) */
            participatingDivisionIds?: string[];
            /** @description Tutup atau buka kembali epic pekerjaan */
            isClosed?: boolean;
        };
        CreateStoryDto: {
            /** @description ID divisi yang bertanggung jawab atas story ini */
            divisionId: string;
            /** @description ID Epic induk (opsional jika pekerjaan rutin divisi) */
            epicId?: string;
            /**
             * @description Judul deliverable story
             * @example Desain Banner Utama & Template Feed IG
             */
            title: string;
            /** @description Kriteria selesai (Definition of Done) */
            doneCriteria?: string;
            /** @description Target tanggal penyelesaian (ISO8601) */
            targetDate?: string;
            /** @description Tag program kerja terkait */
            prokerTag?: string;
            /** @description ID tiket request asal (jika dilahirkan dari request divisi) */
            sourceRequestId?: string;
        };
        UpdateStoryDto: {
            /** @description ID Epic induk (opsional) */
            epicId?: Record<string, never>;
            /** @description Judul story */
            title?: string;
            /** @description Kriteria selesai */
            doneCriteria?: string;
            /** @description Target tanggal */
            targetDate?: string;
            /** @description Tag proker */
            prokerTag?: string;
            /** @description Tutup atau buka kembali story */
            isClosed?: boolean;
        };
        CreateTaskDto: {
            /** @description ID Story induk tempat task ini bernaung */
            storyId: string;
            /**
             * @description Judul unit kerja task
             * @example Buat ilustrasi maskot Moa
             */
            title: string;
            /** @description Deskripsi detail pekerjaan task */
            description?: string;
            /** @description ID anggota tim yang ditugaskan */
            assigneeId?: string;
            /**
             * @description Status awal task
             * @default BACKLOG
             * @enum {string}
             */
            status: "BACKLOG" | "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /**
             * @description Prioritas task
             * @default MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @description Tenggat waktu pengerjaan (ISO8601) */
            dueDate?: string;
            /** @description Posisi urutan task dalam kolom (fractional index) */
            position?: string;
            /** @description Status kendala/blocker */
            isBlocked?: boolean;
            /** @description Alasan blocker/hambatan jika ada */
            blockedReason?: string;
        };
        UpdateTaskDto: {
            /** @description Judul task */
            title?: string;
            /** @description Deskripsi task */
            description?: string;
            /** @description ID anggota tim yang ditugaskan */
            assigneeId?: Record<string, never>;
            /**
             * @description Status task
             * @enum {string}
             */
            status?: "BACKLOG" | "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
            /**
             * @description Prioritas task
             * @enum {string}
             */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @description Tenggat waktu pengerjaan (ISO8601) */
            dueDate?: Record<string, never>;
            /** @description Posisi urutan task dalam kolom */
            position?: string;
            /** @description Status kendala/blocker */
            isBlocked?: boolean;
            /** @description Alasan blocker/hambatan jika ada */
            blockedReason?: Record<string, never>;
            /** @description Jumlah revisi */
            revisionCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login berhasil, token diterbitkan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kredensial salah atau akun belum diaktivasi */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthDto"];
            };
        };
        responses: {
            /** @description Login Google berhasil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email Google tidak terdaftar dalam sistem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getGoogleAuthUrl: {
        parameters: {
            query: {
                redirectUri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallbackGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleCallbackDto"];
            };
        };
        responses: {
            /** @description Login Google berhasil, token diterbitkan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email Google belum terdaftar (sistem tertutup) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token berhasil dirotasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token tidak valid atau kedaluwarsa */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi berhasil dicabut */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data profil user dan divisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            /** @description Profil berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Kata sandi berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateDto"];
            };
        };
        responses: {
            /** @description Akun berhasil diaktivasi dan otomatis login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token aktivasi tidak valid atau kedaluwarsa */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Instruksi reset kata sandi telah diproses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Kata sandi berhasil diubah */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token reset tidak valid atau kedaluwarsa */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ActivityLogsController_getLogs: {
        parameters: {
            query?: {
                /** @description Kata kunci pencarian nama aktor, email, aksi, atau detail */
                search?: string;
                /** @description Filter jenis aksi aktivitas */
                action?: string;
                /** @description Filter tipe entitas (USER, DIVISION_MEMBER, EPIC, dll) */
                entityType?: string;
                /** @description Filter ID entitas tertentu */
                entityId?: string;
                /** @description Kolom pengurutan data */
                sortBy?: "createdAt" | "action" | "actorName";
                /** @description Arah pengurutan data */
                sortOrder?: "asc" | "desc";
                /** @description Nomor halaman (1-indexed) */
                page?: number;
                /** @description Jumlah data per halaman (maksimal 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar activity log beserta metadata paginasi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar divisi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDivisionDto"];
            };
        };
        responses: {
            /** @description Divisi baru berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug divisi sudah digunakan */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail divisi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Divisi tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDivisionDto"];
            };
        };
        responses: {
            /** @description Divisi berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Divisi tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDivisionMemberDto"];
            };
        };
        responses: {
            /** @description Anggota berhasil ditambahkan ke divisi */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Divisi atau Pengguna tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pengguna sudah terdaftar di divisi */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anggota berhasil dihapus dari divisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anggota tidak terdaftar di divisi */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDivisionMemberRoleDto"];
            };
        };
        responses: {
            /** @description Peran anggota berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anggota tidak terdaftar di divisi */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar anggota berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Anggota berhasil didaftarkan dan tautan aktivasi terbit */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email sudah terdaftar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusDto"];
            };
        };
        responses: {
            /** @description Status pengguna berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_addDivision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserDivisionDto"];
            };
        };
        responses: {
            /** @description Keanggotaan divisi berhasil ditambahkan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateDivisionRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                divisionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDivisionRoleDto"];
            };
        };
        responses: {
            /** @description Role divisi berhasil diubah */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_removeDivision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                divisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keanggotaan divisi berhasil dihapus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_moveDivision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveUserDivisionDto"];
            };
        };
        responses: {
            /** @description Anggota berhasil dipindahkan ke divisi baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateGlobalRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserGlobalRoleDto"];
            };
        };
        responses: {
            /** @description Peran Koordinator Mahasiswa Unit berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_resendActivation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tautan aktivasi baru berhasil diterbitkan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpicsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter berdasarkan scope (DIVISION atau CROSS) */
                scope?: string;
                /** @description Filter berdasarkan ID divisi pemilik atau peserta */
                divisionId?: string;
                /** @description Filter status selesai (true = sudah ditutup, false = aktif) */
                isClosed?: string;
                /** @description Pencarian berdasarkan judul, deskripsi, atau tag proker */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar epic berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpicsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEpicDto"];
            };
        };
        responses: {
            /** @description Epic berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tidak memiliki wewenang untuk scope terkait */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpicsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail epic berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Epic tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpicsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Epic berhasil dihapus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Hanya Super Admin atau Kormanit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpicsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEpicDto"];
            };
        };
        responses: {
            /** @description Epic berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Epic tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoriesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter berdasarkan ID divisi */
                divisionId?: string;
                /** @description Filter berdasarkan ID Epic */
                epicId?: string;
                /** @description Filter status selesai (true = sudah ditutup, false = aktif) */
                isClosed?: string;
                /** @description Pencarian berdasarkan judul atau tag proker */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar story berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoryDto"];
            };
        };
        responses: {
            /** @description Story berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan Koordinator divisi terkait */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail story berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Story tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoriesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Story berhasil dihapus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan Koordinator divisi terkait */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoryDto"];
            };
        };
        responses: {
            /** @description Story berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Story tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findAll: {
        parameters: {
            query?: {
                /** @description Filter berdasarkan ID Story */
                storyId?: string;
                /** @description Filter berdasarkan ID divisi pemilik story */
                divisionId?: string;
                /** @description Filter berdasarkan ID assignee/pelaksana */
                assigneeId?: string;
                /** @description Filter berdasarkan status task */
                status?: "BACKLOG" | "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
                /** @description Filter berdasarkan prioritas task */
                priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
                /** @description Pencarian kata kunci judul atau deskripsi task */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar task berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            /** @description Task berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan anggota divisi terkait */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail task berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task berhasil dihapus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan Koordinator divisi terkait */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            /** @description Task berhasil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
